"""A stand-in for LTspice's ``.asc`` -> ``.net`` exporter, for tests without LTspice.

Kept as a non-test helper module (leading underscore) so pytest does not collect
it. It writes the parts of a real LTspice export that a comparison reads, in the
shape LTspice writes them:

* the ``*`` header comments (the sheet's path and the generator line);
* one instance line per symbol, with the ``SpiceLine`` attribute appended the
  way LTspice appends it (``M1 d g s b NMOS l=1u w=10u``);
* each line of a directive ``TEXT`` block on its own line, so a multi-line
  ``.model`` block becomes a card plus ``+`` continuation lines;
* the default models and the install-path ``standard.mos`` library LTspice adds
  to every sheet carrying a MOSFET symbol;
* the ``.backanno`` / ``.end`` tail.

Nets are not traced. Each pin gets a name derived from its instance, so two
exports of the same sheet agree and an added part brings its own nets.
"""

from __future__ import annotations

from pathlib import Path

#: The install directory the exporter writes into its ``.lib`` line.
INSTALL = r"C:\Users\dev\AppData\Local\LTspice\lib\cmp"

_PIN_COUNT = {"nmos": 4, "pmos": 4}


def _symbols_and_directives(asc_text: str) -> tuple[list[dict[str, str]], list[str]]:
    symbols: list[dict[str, str]] = []
    directives: list[str] = []
    for line in asc_text.splitlines():
        if line.startswith("SYMBOL "):
            symbols.append({"symbol": line.split()[1]})
        elif line.startswith("SYMATTR ") and symbols:
            _, key, *rest = line.split(" ", 2)
            symbols[-1][key] = rest[0] if rest else ""
        elif line.startswith("TEXT ") and "!" in line:
            # The .asc stores a multi-line TEXT block with literal "\n" breaks.
            directives.extend(line.split("!", 1)[1].split("\\n"))
    return symbols, directives


def netlist_text(asc_path: Path) -> str:
    """The netlist LTspice would write for ``asc_path``."""
    symbols, directives = _symbols_and_directives(asc_path.read_text(encoding="latin-1"))
    lines = [f"* {asc_path}", "* Generated by LTspice 26.0.2 for Windows."]
    for sym in symbols:
        ref = sym["InstName"]
        pins = " ".join(f"{ref}_{n}" for n in range(1, _PIN_COUNT.get(sym["symbol"], 2) + 1))
        tail = " ".join(sym[key] for key in ("Value", "SpiceLine") if sym.get(key))
        lines.append(f"{ref} {pins} {tail}".rstrip())
    if any(sym["symbol"] in _PIN_COUNT for sym in symbols):
        lines += [".model NMOS NMOS", ".model PMOS PMOS", f".lib {INSTALL}\\standard.mos"]
    lines += directives
    lines += [".backanno", ".end"]
    return "\n".join(lines) + "\n"


def create_netlist(_simulator_cls, asc_path, timeout: float = 0, **_kw) -> Path:
    """Drop-in for ``verify._create_netlist``: writes the sibling ``.net``."""
    asc = Path(asc_path)
    net = asc.with_suffix(".net")
    net.write_text(netlist_text(asc), encoding="utf-8")
    return net


async def export_asc_to_netlist(asc_copy: Path, _state) -> str:
    """Drop-in for ``schematic_edit._export_asc_to_netlist``."""
    return netlist_text(asc_copy)
